id: P87EDAFFA
initial_creation_type: input
source_metadata:
  title: Minyak Kunzang Sönam Series
  language: es
  description: 'Texts by and about Minyak Kunzang Sönam (mi nyag kun bzang bsod nams,
    1823–1905) alias Thubten Chökyi Drakpa (thub bstan chos kyi grags pa) :'
  volume:
    b8324e91319c4b479f6a42976198e895:
      title: Overview of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
created_at: '2022-03-01T00:49:12.157542'
last_modified_at: '2022-03-01T00:49:12.157544'
